server:
  port: 8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/eureka/}

spring:
  profiles:
    active: native
  application:
    name: config-server


