spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cards
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
  api-docs:
      enabled: true
  swagger-ui:
      enabled: true
server:
    port: 8087
    servlet:
      context-path: /cards

eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/eureka/}
    instance:
      hostname: localhost

management:
    endpoints:
      web:
      exposure:
        include: "*"