spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/orders
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
      ddl-auto: update
      show-sql: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/eureka/}
  instance:
    hostname: localhost
server:
  port: 8085
  servlet:
    context-path: /orders

payment:
  url: http://localhost:8086/payment/createPayment?amount={amount}&orderId={orderId}&userId={userId}
