spring:
    application:
      name: product-service
    datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/products
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:root}
      driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
          show-sql: true
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
management:
    tracing:
      sampling:
        probability: 1.0
server:
    port: 8084
    servlet:
      context-path: /products
eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/eureka/}
    instance:
      hostname: localhost

