server:
  port: 8083
  servlet:
    context-path: /users
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka/
  instance:
    hostname: localhost
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
management:
  tracing:
    sampling:
      probability: 1.0





